### ISSUE TITLE
Ability to recive the transmitted GMSk signal on Soundmodem

### ISSUE THREAD

**Issue by rnbokade** [NotBlackMagic/VUHFRadio#2]
Now that you have the setup ready can you transmit some AX.25 frame and receive on a baofeng or similar FM radio, while feeding its output audio to the computer via audio cable and the check whether the sound modem decodes it properly or not. I mean High-speed sound modem. Do the same with AFSk transmissions but with normal Soundmodem. If the sound modem doesn't works with the 9600 modes see if you can get it to decode by changing some transmit paramaters. You can find it from here http://uz7.ho.ua/packetradio.htm. Frankly, I am interested in this, since if it works, then your work will become a boon for satellite builders as that will enable the transmitted signal to be received by hams around the world, incase your design is used in a satellite itself.

**Comment by NotBlackMagic** [comment]
Thank you for bringing me SoundModem (HS) to my attention. I have now tested both AFSK-1200 and FSK-9600 with it, transmitted from the VUHFRadio and received on the PC through an RTL.SDR and SDR# as the FM receiver and then SoundModem as the "TNC". The used configuration can be found in the newly added "memoryChannelConfigs".
My motivation for this project was/is to use it to help debug and communicate with our University Cubesat that is under development and which uses HAM Radio compatible modulations as the core modulations. Both AFSK-1200 and FSK-9600 and I already had tested the VUHFRadio with our TT&C and Pluto-SDR/GNU Radio ground station.
